apiVersion: v1
kind: Service
metadata:
  name: devops-java-service
spec:
  type: LoadBalancer
  selector:
    app: devops-java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


